---
- hosts: localhost
  gather_facts: false
  vars_files:
    - passes.yml
  vars:
    git_checkout_path: /tmp/ocp-auto
    inventory_file: "{{ git_checkout_path }}/hosts"
    project_repo: github.com/jduncan-rva/ocp-auto-scale-ansible.git
    tower_api_url: https://192.168.122.120/api/v2
    host_ip: 192.168.122.108
    inventory_id: 6
    new_host_parameters: openshift_schedulable=true

  tasks:
  - name: create new_nodes inventory group
    uri:
      url: "{{ tower_api_url }}/groups/"
      method: POST
      user: admin
      password: redhat
      validate_certs: no
      status_code: 201
      body_format: json
      body: "{'name':'new_nodes','inventory':'{{ inventory_id }}'}"
    tags:
      - provision_3_1

  - name: update inventory with new host
    uri:
      url: "{{ tower_api_url }}/hosts/"
      method: POST
      user: admin
      password: redhat
      validate_certs: no
      status_code: 201
      body_format: json
      body: "{'name':'{{ host_ip }}','inventory':'{{ inventory_id }}','variables':'{{ new_host_parameters }}'}"
    tags:
      - provision_3_1

  - name: check out repository
    git:
      accept_hostkey: yes
      repo: "https://{{ project_repo }}"
      dest: "{{ git_checkout_path }}"
      force: yes
    tags:
      - provision
      - cleanup

  - name: add new_nodes to OSEv3:children
    lineinfile:
      path: "{{ inventory_file }}"
      insertafter: '^etcd$'
      line: 'new_nodes'
    tags:
      - provision

  - name: add new_nodes group
    blockinfile:
      path: "{{ inventory_file }}"
      insertafter: EOF
      block: |
        [new_nodes]
        {{ host_ip }} {{ new_host_parameters }}
    tags:
      - provision

  - name: clean up new_nodes group
    blockinfile:
      path: "{{ inventory_file }}"
      state: absent
      insertafter: EOF
      block: |

        [new_nodes]
        {{ host_ip }} {{ new_host_parameters }}
    tags:
     - cleanup

  - name: clean up new_nodes inventory
    lineinfile:
      path: "{{ inventory_file }}"
      state: absent
      insertafter: '^etcd$'
      line: 'new_nodes'
    tags:
      - cleanup

  - name: move host to regular nodes group
    lineinfile:
      path: "{{ inventory_file }}"
      insertafter: '^\[nodes\]'
      line: "{{ host_ip }} {{ new_host_parameters }}"
    tags:
      - cleanup

  - name: commit changes to repo
    shell: git config user.name "Tower User" && git config user.email "Tower@tower.com" && git add -A && git commit -m "updated by Ansible at $(date +%Y%m%d%H%M%S)"
    args:
      chdir: "{{ git_checkout_path }}"
    tags:
      - provision
      - cleanup

  - name: push updated project repo
    shell: git push https://{{ github_user }}:{{ github_pass }}@{{ project_repo }} --all
    args:
      chdir: "{{ git_checkout_path }}"
    tags:
      - provision
      - cleanup

  - name: remove temporary directory
    file:
      name: "{{ git_checkout_path }}"
      state: absent
    tags:
      - provision
      - cleanup
